### ISSUE TITLE
The link in Implementation page  https://github.com/nemequ/simde/wiki/Implementing-a-New-Function seems to be broken

### ISSUE THREAD

**Issue by Adarsh-NP** [nemequ/simde#111]
The link to avx2.c under adding the tests seems to be broken. I guess the link would be just test/x86/avx2.c. 
kindly look into it.

**Comment by nemequ** [comment]
Yep, you're right, it should go to test/x86/avx2.c.  That file moved a while back, guess I never updated the guide.  It's fixed now, thanks for pointing it out!
