### ISSUE TITLE
GSoD participation

### ISSUE THREAD

**Issue by FaresSalem** [nemequ/simde#120]
Google Season of Docs 2020 was announced this week in case you’d like to participate.
https://developers.google.com/season-of-docs

**Comment by FaresSalem** [comment]
OBF didn’t participate the last season though so maybe you could tell them as well, so you can join with them I think.

**Comment by nemequ** [comment]
I'm open to this, I'm just not sure SIMDe is a good fit.  This would be great for a user-facing project, but the type of documentation we need really requires a programmer with fairly specialized knowledge and would be really hard for most technical writers.  I'll leave it open for a while in case anyone has some ideas, though.

@mr-c, maybe you can think of some other projects that could benefit from this?

**Comment by nemequ** [comment]
I guess nobody else has any ideas, either.  Closing, but if anyone thinks of anything please feel free to reopen or comment.

Anyways, thanks for letting us know about this, Fares!  Please don't be shy about suggestions like this in the future :)
