### ISSUE TITLE
The build for the tests fails on clang-10, 9, armv7

### ISSUE THREAD

**Issue by junaruga** [nemequ/simde#129]
On the master branch commit: `434b6272e1db863e743cc994f760274d2ecd1e8d` applying [this patch](https://github.com/nemequ/simde/issues/124#issuecomment-605676540), I faced the failure of the `make` after `cmake ..` for the unit tests with clang 10 and 9 on Fedora armv7 environment. Here is [the log](https://gist.github.com/junaruga/b4d3b8f952974afd972ba38825fd1a68).

I am seeing the similar error on clang-7 case on Drone CI (https://github.com/nemequ/simde/pull/128) .

Do you have any idea to fix? Thank you.

```
$ clang --version
clang version 10.0.0 (Fedora 10.0.0-0.11.rc6.fc33)
Target: armv7l-unknown-linux-gnueabihf
Thread model: posix
InstalledDir: /usr/bin

$ clang++ --version
clang version 10.0.0 (Fedora 10.0.0-0.11.rc6.fc33)
Target: armv7l-unknown-linux-gnueabihf
Thread model: posix
InstalledDir: /usr/bin
```

```
$ mkdir test/build-clang
$ cd test/build-clang
$ CC=clang CXX=clang++ cmake ..
$ make -O -j5 V=1 VERBOSE=1
...
/builddir/build/BUILD/simde-434b6272e1db863e743cc994f760274d2ecd1e8d/test/x86/../../simde/x86/sse2.h:2344:54: error: no member named 'neon_f64' in 'simde__m128d_private'
  r_.neon_f64 = vsetq_lane_f64((simde_float64) b, a_.neon_f64, 0);
                                                  ~~ ^
...
```

**Comment by nemequ** [comment]
Sorry, forgot to comment, but this should be fixed.
