### ISSUE TITLE
armv7hl tests fail with gcc 10.0.1 with -O2 and some flags 

### ISSUE THREAD

**Issue by junaruga** [nemequ/simde#156]
When running the tests on the master branch, the latest commit: `9efa34cddce5a5281f6909d48b11d5639ec0b519` with gcc 10.0.1 with `-O2` and some flags on Fedora rawhide (= 33), it was failed on armv7hl and aarch64. For aarch64, I reported it to https://github.com/nemequ/simde/issues/147#issuecomment-609459714 . For other architectures x86_64, ppc64le, s390x, i686, the tests were okay.

```
$ gcc --version
gcc (GCC) 10.0.1 20200328 (Red Hat 10.0.1-0.11)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ --version
g++ (GCC) 10.0.1 20200328 (Red Hat 10.0.1-0.11)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ mkdir test/build-gcc-with-flags

$ pushd test/build-gcc-with-flags

$ CC=gcc CXX=g++ cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON '-DCMAKE_C_FLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard' '-DCMAKE_CXX_FLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard' ..

$ /usr/bin/make -O -j5 V=1 VERBOSE=1
...
/x86/sse4_1/mm_insert_epi64/emul/cpp [ ERROR ]
/x86/sse4_1/mm_insert_ps/emul/cpp    Error: /builddir/build/BUILD/simde-9efa34cddce5a5281f6909d48b11d5639ec0b519/test/build-gcc-with-flags/x86/sse4.1.cpp:1971: assertion failed: r.i64[0] == test_vec[i].r.i64[0] (0 == -9193337552220811958)
Error: child killed by signal 6 (Aborted)
[ OK    ] [ 0.00001860 / 0.00001737 CPU ]
...
/x86/sse4_1/mm_minpos_epu16/emul/cpp [ ERROR ]
/x86/sse4_1/mm_mpsadbw_epu8/emul/cpp Error: /builddir/build/BUILD/simde-9efa34cddce5a5281f6909d48b11d5639ec0b519/test/build-gcc-with-flags/x86/sse4.1.cpp:2562: assertion failed: r.u16[4] == test_vec[i].r.u16[4] (65535 == 0)
Error: child killed by signal 6 (Aborted)
[ OK    ] [ 0.00003745 / 0.00003615 CPU ]
...
1818 of 1820 (100%) tests successful, 0 (0%) test skipped.
```

Here is [the full log](https://gist.github.com/junaruga/641a2bcf1d96cd1274b57b935793ab15).

Thank you.

**Comment by nemequ** [comment]
Apparently you and Michael have found another use case for SIMDe: a pretty good stress test for GCC :)

I'll look into this ASAP, thanks for reporting (and testing).

**Comment by junaruga** [comment]
> Apparently you and Michael have found another use case for SIMDe: a pretty good stress test for GCC :)

Yeah, I tested simde with Fedora's recommended gcc flags value that is `%{build_cflags}` (= RPM macro) for `C_FLAGS` and `%{build_cxxflags}` for `CXX_FLAGS`.
The macro value is a little bit different for each CPU architecture.

Here is the original code in the RPM spec file `simde.spec`.

```
echo "=== 1.2. tests on gcc with flags ==="
mkdir test/build-gcc-with-flags
pushd test/build-gcc-with-flags
CC=gcc CXX=g++ cmake \
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
  -DCMAKE_C_FLAGS="%{build_cflags}" \
  -DCMAKE_CXX_FLAGS="%{build_cxxflags}" \
  ..
%make_build
./run-tests
popd
```

You can see [this page](https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/master/f/buildflags.md) for the flag's explanation.

> I'll look into this ASAP, thanks for reporting (and testing).

Thanks for checking.

**Comment by nemequ** [comment]
I'm working on this.  It took me a while to get an environment where I could reproduce it, but that happened a couple hours ago.  I think they're both compiler bugs, so I'm generating reduced test cases now.  I should have this fixed in SIMDe within 24 hours.

**Comment by nemequ** [comment]
Okay, a couple days after I thought I'd be done with this issue…

I'm not sure if the insert issue is [GCC 94482](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94482) or not, but I have [a reduced test case](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94482#c25) which the GCC folks should be able to use.

I managed to reproduce these from x86_64 with a cross-compiler and qemu, so now C-Reduce only takes 30-45 minutes per run instead of ~16 hours on a Raspberry Pi 3.  I'm getting close to a good test case for the minpos problem, it's just tricky getting something that doesn't trigger warnings and passes asan and ubsan.

Sorry this is taking so long, but I really want to make sure they get fixed in GCC instead of just working around them in SIMDe.

**Comment by junaruga** [comment]
> Sorry this is taking so long, but I really want to make sure they get fixed in GCC instead of just working around them in SIMDe.

@nemequ Don't worry. It's alright! It's great to see you work to help that they get fixed in GCC.

**Comment by nemequ** [comment]
This seems to be fixed with the latest version of GCC.

For the insert issue it was probably that GCC bug I linked to.   For mpsadbw, I'm not sure what the relevant change was but I can't reproduce it anymore with the GCC 10.1 release candidate.

Please give it another try when you have time.

**Comment by junaruga** [comment]
> Please give it another try when you have time.

Sure. Thank you for fixing it. I let you know after I try it later.

**Comment by junaruga** [comment]
I confirmed it was fixed!

**Comment by nemequ** [comment]
That's a big relief, thanks.  That minpos one was evil, really glad that's behind us :)
