### ISSUE TITLE
Typo in NEON-related code

### ISSUE THREAD

**Issue by yekm** [nemequ/simde#16]
https://github.com/nemequ/simde/blob/2dd21c701ec59043354be6f04931a340df94ec0f/simde/x86/sse4.1.h#L687

I think everything should be unsigned on this line.

Also, take a look at the `run-tests` output on the i.MX6 https://gist.github.com/yekm/80843dae40e4ca326483cf16fe53f81d (I am not sure if I compiled everything correctly)

**Comment by nemequ** [comment]
Yeah, s/i/u/ sounds right... Does it work as expected with that change? I 
won't have a chance to test for a few days...

On May 14, 2018 08:09:21 Pavel <notifications@github.com> wrote:
> https://github.com/nemequ/simde/blob/2dd21c701ec59043354be6f04931a340df94ec0f/simde/x86/sse4.1.h#L687
> I think everything should be unsigned on this line.
> Also, take a look at the run-tests output on the i.MX6 
> https://gist.github.com/yekm/80843dae40e4ca326483cf16fe53f81d (I am not 
> sure if I compiled everything correctly)
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail

**Comment by yekm** [comment]
It does not compile without that change.

Regarding that test. I forgot to set my cflags `-flax-vector-conversions -fopenmp-simd -mthumb -O3 -march=armv7-a -mcpu=cortex-a9 -mtune=cortex-a9 -mfpu=neon`. Not sure what flag is actually made a difference (I remember that my compiler is already configured to optimize for cortex-a9 anyway), but test is 100% successful now.

**Comment by nemequ** [comment]
Merged #17, sorry again for the delay.
