### ISSUE TITLE
Implement functions for Leopard

### ISSUE THREAD

**Issue by nemequ** [nemequ/simde#18]
@catid mentioned [Leopard](https://github.com/catid/leopard) on Twitter as a potential target for SIMDe.  AFAICT (`grep -hoP '_mm(256)?_[a-z0-9_]+' *.{cpp,h} | sort | uniq`) only 7 functions are currently missing:

* [x] _mm256_and_si256
* [x] _mm256_broadcastsi128_si256
* [x] _mm256_loadu_si256
* [x] _mm256_shuffle_epi8
* [x] _mm256_srli_epi64
* [x] _mm256_storeu_si256
* [x] _mm256_xor_si256

I'm not sure how competitive a SIMDe implementation would be, but it's certainly worth a try.

**Comment by catid** [comment]
All these functions you listed have been ported to ARM already in this other library of mine: https://github.com/catid/gf256

I've just been too busy with other projects to port this one yet

**Comment by catid** [comment]
The gf256 library is used by wirehair and cm256, which makes them portable already..

**Comment by nemequ** [comment]
Okay, the SIMDe side is done, just need to throw together a SIMDe port of Leopard which should be pretty straightforward (basically adding an include and adding a "simde_" prefix to some function calls).

**Comment by nemequ** [comment]
I just pushed a [simde branch](https://github.com/nemequ/leopard/tree/simde) to my Leopard repo.  I haven't really tested much, though it does seem to work without any special flags (i.e., SSE2 only).  The only real changes are the ones in LeopardCommon.h; everything else is just s/_mm_/simde_mm_/ and s/_mm256_/simde_mm256_/.

Travis [has some failures](https://travis-ci.org/nemequ/leopard) on older compilers (GCC ≤ 5) and MSVC [doesn't seem to work](https://ci.appveyor.com/project/quixdb/leopard)… I think it's because Leopard is C++ not C, so I definitely have some work to do. Still, I think it's a pretty good start.

ARM performance will depend on what functions are being used; stuff like and, add, xor, etc. should be pretty fast, but shuffle-heavy code will probably be painful.  Right now the focus for SIMDe is adding portable implementations, once that's done we can focus more on optimization (starting with the functions which actually get used).

**Comment by catid** [comment]
Awesome

**Comment by nemequ** [comment]
Done.  Everything should be working properly now.
