### ISSUE TITLE
Supporting cmake 2.8 to run the tests?

### ISSUE THREAD

**Issue by junaruga** [nemequ/simde#183]
I am trying to run the tests on EPEL 7 (= RHEL 7) environment.
`cmake` version 2.8.12  is used, and I got following error.

How do you think supporting the build with cmake 2.8?
If possible, I want to run the tests on the environment.

```
+ echo '=== 1.1. tests on gcc without flags ==='
+ mkdir test/build-gcc
~/build/BUILD/simde-29b911059dd06bc1e4c30d8922871a4b239279e3/test/build-gcc ~/build/BUILD/simde-29b911059dd06bc1e4c30d8922871a4b239279e3
+ pushd test/build-gcc
+ CC=gcc
+ CXX=g++
+ cmake ..
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.0 or higher is required.  You are running version 2.8.12.2
-- Configuring incomplete, errors occurred!
```

```
$ cat test/CMakeLists.txt
cmake_minimum_required(VERSION 3.0)
...
```

**Comment by nemequ** [comment]
Hmm.  2.8 is pretty old, and if I remember correctly there were some pretty significant changes in CMake around that time that made a lot of stuff much easier.  I'll take a look and see if I can get it working in a CentOS 7 VM, but I don't want to make any promises.

If it doesn't work out, maybe it would be possible to use pip to install current meson & ninja and use that to build?

**Comment by junaruga** [comment]
Yeah it's alright.

> If it doesn't work out, maybe it would be possible to use pip to install current meson & ninja and use that to build?

Yes. I would. The meson and ninja workaround can be used for this kind of situation.

**Comment by junaruga** [comment]
I was able to build by installing `meson` and `ninja-build` RPM.

The steps are like this.
One note is `ninja-build-1.7.2-2.el7.x86_64` only has `ninja-build` command. It does not have `ninja` command.

```
yum install -y epel-release
yum install -y meson ninja-build git-core gcc gcc-c++ clang
```

```
mkdir -p build
cd build
meson ..
ninja-build -v
./test/run-tests
```

Feel free to close this ticket. Thanks!
