### ISSUE TITLE
automated ARMv7 testing

### ISSUE THREAD

**Issue by jeffdaily** [nemequ/simde#20]
Under https://github.com/nemequ/simde#hardware you say ARMv7 is regularly tested.  I don't see any use of cross-compiling or qemu in the .travis.yml so I was wondering how you accomplish the testing of the native neon instructions?

**Comment by nemequ** [comment]
I've just been manually testing using a Raspberry Pi (or a Beagle Board, or a Banana Pi, etc.; whatever I have plugged in).

**Comment by jeffdaily** [comment]
I submitted #21 today, but one of the two cross-compiled environments that I added to the travis build is failing in a place I am not sure how to fix.
