### ISSUE TITLE
Configure Travis to kill prior builds if a new commit is added to a branch/PR

### ISSUE THREAD

**Issue by mr-c** [nemequ/simde#247]
@nemequ The setting should be at https://travis-ci.org/github/nemequ/simde/settings

>  Auto Cancellation

> Auto Cancellation allows you to only run builds for the latest commits in the queue. This setting can be applied to builds for Branch builds and Pull Request builds separately. Builds will only be canceled if they are waiting to run, allowing for any running jobs to finish.

I recommend turning both on, as it will speed up things for everyone.

**Comment by nemequ** [comment]
This sounds like a good idea, but they're both already on.

Maybe it doesn't work if the PR is from the same repo (i.e., from wip/gfni to master), since that would be considered a branch build not a PR?
