### ISSUE TITLE
Travis-CI icc tests failing

### ISSUE THREAD

**Issue by rosbif** [nemequ/simde#252]
Some tests using icc in Travis-CI fail when they succeed on all other platforms.
This seems to be due to icc generating bad code if it cannot vectorize.
For the gf2p8mul intrinsics and their mask versions in gfni.[hc] currently in WIP:
- all the 128-bit versions succeed
- all the 256-bit and 512-bit versions fail

This is very surprising as, while the 128-bit versions which succeed are complex, the 256-bit and 512-bit versions currently simply call the 128-bit versions two or four times respectively.
Michael has confirmed that conditionally removing SIMDE__VECTORIZE for icc is sufficient for all the tests to succeed.

**Comment by mr-c** [comment]
Hello @rosbif 

Yep, `icc` has given us some problems in the past. Currently it is working, even on the `wip/gfni` branch: https://travis-ci.org/github/nemequ/simde/jobs/680974249

Feel free to ignore `icc` and I'm sure that @nemequ and myself can fix up any issues before the final merge.

**Comment by rosbif** [comment]
That is great news.
What was causing icc to behave like this?

**Comment by mr-c** [comment]
> That is great news.

Yep!

> What was causing icc to behave like this?

It wasn't icc, it was the package archive itself

**Comment by nemequ** [comment]
Regarding `SIMDE__VECTORIZE`: it looks like this is a problem that I've already [reported to Intel](https://software.intel.com/en-us/forums/intel-c-compiler/topic/850742).  It's the reason the loops with the fallbacks on previous ISA extensions are manually unrolled in other functions.

I'm really not sure what to do about this.  `#ifdef`ing out the OMP pragma fixes the issue in some cases but not all, and unrolling the loops is really terrible (and potentially carries a performance penalty in other compilers).  Working around an occasional bug isn't a big deal, but issues like this where the compiler can't handle the pattern which we really need to replicate to a *lot* of functions is bad.  I'm very tempted to drop support for ICC until they fix their compiler…
