### ISSUE TITLE
Should simde_mm_setone_pd be renamed?

### ISSUE THREAD

**Issue by mr-c** [nemequ/simde#263]

**Comment by nemequ** [comment]
Why?  To what?

`simde_x_mm_setone_pd` would make sense, I guess.  I tried to make it consistent with `_mm_setzero_pd`…

**Comment by mr-c** [comment]
> Why?

For consistency; to set user expectations; to ease spot checking 

> simde_x_mm_setone_pd

:+1:

**Comment by nemequ** [comment]
Okay, moving it into simde_x_ makes sense, I just wanted to make sure you weren't objecting to the "setone" part.

Should be fixed soon, just waiting on CI, thanks for noticing this.
