### ISSUE TITLE
gcc 5.4 + -Werror=unused-but-set-variable leads to build failures

### ISSUE THREAD

**Issue by mr-c** [nemequ/simde#277]
MMseqs2 tests their project using Ubuntu 16.04 and `-Werror=unused-but-set-variable` so they see the following build failures:

``` make
[ 30%] Building CXX object src/CMakeFiles/mmseqs-framework.dir/alignment/Alignment.cpp.o
In file included from /home/vsts/work/1/s/src/commons/itoa.h:29:0,
                 from /home/vsts/work/1/s/src/alignment/Matcher.h:13,
                 from /home/vsts/work/1/s/src/alignment/CompressedA3M.h:4,
                 from /home/vsts/work/1/s/src/alignment/CompressedA3M.cpp:7:
/home/vsts/work/1/s/lib/simde/simde/x86/sse2.h: In function ‘simde__m128i simde_x_mm_not_si128(simde__m128i)’:
/home/vsts/work/1/s/lib/simde/simde/x86/sse2.h:5928:5: error: variable ‘a_’ set but not used [-Werror=unused-but-set-variable]
     a_ = simde__m128i_to_private(a);
     ^
```
https://dev.azure.com/themartinsteinegger/mmseqs2/_build/results?buildId=579&view=logs&j=ea4a7635-651a-5c6d-82fb-18d73c63d535&t=924f333b-d698-5570-5630-b23a5cbcb584&l=169

Here's a Dockerfile to reproduce the situation: https://github.com/nemequ/simde/blob/docker_local_testing/test/docker/Dockerfile.Ubuntu1604

**Comment by mr-c** [comment]
This is not an issue with Ubuntu 18.04's GCC 7.4, as shown via https://github.com/nemequ/simde/blob/docker_local_testing/test/docker/Dockerfile.Ubuntu1804

**Comment by nemequ** [comment]
I remember seeing something similar a while back and figured out it was a false positive.  Not sure it was the same function, but I'll take a look.

If it is a false positive I can probably just add `-Wunused-but-set-variables` to the list of errors to ignore in SIMDe headers, and restrict it to very old versions of gcc.

**Comment by nemequ** [comment]
Yep, it's a false positive. There are actually a bunch of them, and AFAICT they're all false positives. It only happens in C++ mode, and disappears in GCC 6. b084f4d438820bdc7765095a0cb8bdf75320c722 silences the warning and adds a xenial build to GitHub Actions.

**Comment by mr-c** [comment]
Thanks!
