### ISSUE TITLE
type confustion on ppc64el

### ISSUE THREAD

**Issue by mwhudson** [nemequ/simde#325]
Hi,

Debian uses simde to compile some software I've never heard of (pbcopper) on non-intel architectures. It fails to build on Ubuntu ppc64el (little endian powerpc 64 bit) and I distilled the failure down to this:

```shellsession
$ cat test.c
//#define SIMDE_NO_NATIVE
#include "simde/x86/sse2.h"

void f(void)
{
    simde__m128i v;
    v = simde_mm_slli_si128(v, 1);
}
$ cc -c test.c
In file included from /usr/include/simde/simde-features.h:301,
                 from /usr/include/simde/simde-common.h:38,
                 from /usr/include/simde/x86/mmx.h:30,
                 from /usr/include/simde/x86/sse.h:33,
                 from /usr/include/simde/x86/sse2.h:35,
                 from test.c:2:
test.c: In function 'f':
test.c:7:9: error: incompatible types when assigning to type 'simde__m128i' {aka '__vector(4) float'} from type '__vector unsigned char' {aka '__vector(16) unsigned char'}
    7 |     v = simde_mm_slli_si128(v, 1);
      |         ^~~~~~~~~~~~~~~~~~~
```

Uncommenting the SIMDE_NO_NATIVE makes it build. It compiles without that on amd64. I'm very very far from an expert on SSE intrinsics, but it seems like this should work?

**Comment by mr-c** [comment]
Hello @mwhudson , I'm the Debian Maintainer for SIMDe and a contributor. This was fixed recently, thanks! I'll upload a new package today.

**Comment by mr-c** [comment]
https://tracker.debian.org/news/1147647/accepted-simde-000git20200526-1-source-into-unstable/

**Comment by nemequ** [comment]
Sorry about this, it was my fault; I made a change a couple weeks ago that had the unintended side-effect of making our tests only check the portable fallbacks and not the accelerated implementations, which I only noticed this weekend.  During that period some bad code made it through our CI, which is normally very good at catching stuff like this :(
