### ISSUE TITLE
Need instructions for android integration

### ISSUE THREAD

**Issue by kafan1986** [nemequ/simde#39]
I am integrating this code in android. I need to call SSE2 instructions in my c++ code on arm cpu platform. What else files do I need apart from the below listed files:
a) hedley.h
b) mmx.h
c) simde-arch.h
d) simde-common.h
e) sse.h
f) sse2.h

**Comment by nemequ** [comment]
If all you need is SSE2 I believe that should be sufficient.  In the future I may make more of an effort to use the SIMD.js stuff as a common layer, but that's pretty far off.

That said, I'd suggest either just copying the entire tree into a subdirectory of your project.  Better yet, if you're using git you can use a submodule or subtree, or if you're using svn you can use external items ([GitHub supports subversion clients](https://help.github.com/en/articles/support-for-subversion-clients)).  This makes it much easier to track changes in SIMDe, such as bug fixes, optimizations, and support for new implementations (e.g., NEON/POWER/MSA/etc. implementations of SSE2 functions).

**Comment by kafan1986** [comment]
I copies the entire simd directory. Now, unlike the other SSE2NEON library which mentioned to replace 

//#include <emmintrin.h>
//#include <pmmintrin.h>

with the SSE2NEON.h file. 

Which header file should I include now for this library?

**Comment by nemequ** [comment]
For SSE2, you just need to include simde/x86/sse2.h; it will include its dependencies.

See https://github.com/nemequ/simde#usage for more information.
