### ISSUE TITLE
Support for `popcnt` instruction?

### ISSUE THREAD

**Issue by marmeladema** [nemequ/simde#42]
I know its not a proper SIMD instruction but its nonetheless a useful instruction which appears at the same time as SSE4: https://en.wikipedia.org/wiki/SSE4#POPCNT_and_LZCNT

Moreover, NEON instruction set has a similar `cnt` instruction that can be used for ARM architecture.

It should probably go into its own header flle `popcnt.h` ?

**Comment by nemequ** [comment]
I have an implementation [in portable-snippets](https://github.com/nemequ/portable-snippets/blob/master/builtin/builtin.h#L742), which I think is a more appropriate place for this.

**Comment by mr-c** [comment]
@nemequ Any advice for `_lzcnt_u32` ?

**Comment by nemequ** [comment]
Depends on how much portability you need.  There is a [`psnip_builtin_clz32`](https://github.com/nemequ/portable-snippets/blob/26496acb37ab46ee249ea19d45381da6955d89c4/builtin/builtin.h#L480) in portable-snippets if you're good with that.

If you don't want to use portable-snippets `__builtin_clz` might be a good option.  MSVC doesn't support it (it has `_BitScanReverse`), but gcc, clang, icc, and armcc all do support `__builtin_clz`.  Note that that also assumes `sizeof(int) == sizeof(uint32_t)`, so you may want to test to see if you should be using `__builtin_clzl` or `__builtin_clzll` instead, or if `sizeof(int) > sizeof(uint32_t)` you could just use `__builtin_clz` and subtract `(sizeof(int) - sizeof(uint32_t)) * CHAR_BIT`.

If you want something fully portable and don't really care about performance I suggest [this](https://graphics.stanford.edu/~seander/bithacks.html#IntegerLogDeBruijn), which is what psnip uses for the portable fallback.

**Comment by mirh** [comment]
https://github.com/kimwalisch/libpopcnt
http://www.dalkescientific.com/writings/diary/archive/2011/11/02/faster_popcount_update.html
There are probably faster ways than that fallback btw.

**Comment by mr-c** [comment]
@mirh great find, thanks!
