### ISSUE TITLE
FMA support

### ISSUE THREAD

**Issue by mr-c** [nemequ/simde#58]
For [RAxML](https://github.com/stamatak/standard-RAxML/)
- [x] _mm256_fmadd_pd

others:
- [x] _mm_fmadd_pd 
- [x] _mm_fmadd_ps 
- [x] _mm256_fmadd_ps 
- [ ] _mm_fmadd_sd 
- [ ] _mm_fmadd_ss 
- [ ] _mm_fmaddsub_pd
- [ ] _mm256_fmaddsub_pd
- [ ] _mm_fmaddsub_ps
- [ ] _mm256_fmaddsub_ps
- [ ] _mm_fmsub_pd
- [ ] _mm256_fmsub_pd
- [ ] _mm_fmsub_ps
- [ ] _mm256_fmsub_ps
- [ ] _mm_fmsub_sd
- [ ] _mm_fmsub_ss
- [ ] _mm_fmsubadd_pd
- [ ] _mm256_fmsubadd_pd
- [ ] _mm_fmsubadd_ps
- [ ] _mm256_fmsubadd_ps
- [ ] _mm_fnmadd_pd
- [ ] _mm256_fnmadd_pd
- [ ] _mm_fnmadd_ps
- [ ] _mm256_fnmadd_ps
- [ ] _mm_fnmadd_sd
- [ ] _mm_fnmadd_ss
- [ ] _mm_fnmsub_pd
- [ ] _mm256_fnmsub_pd
- [ ] _mm_fnmsub_ps
- [ ] _mm256_fnmsub_ps
- [ ] _mm_fnmsub_sd
- [ ] _mm_fnmsub_ss

**Comment by nemequ** [comment]
4166fefd86956722fe78b3afa633e91acc94cc1f adds _mm256_fmadd_pd, so hopefully RAxML works now.

**Comment by mr-c** [comment]
@nemequ Thanks! I've refreshed the SIMDe copy in RAxML. They have their own makefiles for AVX, SSE3, and SIMD-free compilation that we are using in the Debian Package, so it'll take me a bit longer to adapt them for compilation at decreasing levels of SIMD support.

**Comment by nemequ** [comment]
FMA support is complete as of 306d1a1371f36493c297b8a4ed50079e14108e68.

**Comment by mr-c** [comment]
Woohoo!
