### ISSUE TITLE
error: invalid static_cast from type 'simde_float64*' {aka 'double*'} to type 'simde__m256d*'

### ISSUE THREAD

**Issue by mr-c** [nemequ/simde#60]
While using https://travis-ci.org/nemequ/simde/builds/625813486 to improve https://salsa.debian.org/med-team/last-align/

```
../debian/include/simde/x86/../hedley.h:1367:59: error: invalid static_cast from type 'simde_float32*' {aka 'float*'} to type 'simde__m256*'
 1367 | #  define HEDLEY_STATIC_CAST(T, expr) (static_cast<T>(expr))
      |                                                           ^
../debian/include/simde/x86/../simde-common.h:68:45: note: in expansion of macro 'HEDLEY_STATIC_CAST'
   68 | #  define SIMDE_CAST_ALIGN(alignment, T, v) HEDLEY_STATIC_CAST(T, v)
      |                                             ^~~~~~~~~~~~~~~~~~
../debian/include/simde/x86/avx.h:4323:4: note: in expansion of macro 'SIMDE_CAST_ALIGN'
 4323 |   *SIMDE_CAST_ALIGN(32, simde__m256*, mem_addr) = a;
      |    ^~~~~~~~~~~~~~~~
../debian/include/simde/x86/avx.h: In function 'void simde_mm256_stream_pd(simde_float64*, simde__m256d)':
../debian/include/simde/x86/../hedley.h:1367:59: error: invalid static_cast from type 'simde_float64*' {aka 'double*'} to type 'simde__m256d*'
 1367 | #  define HEDLEY_STATIC_CAST(T, expr) (static_cast<T>(expr))
      |                                                           ^
../debian/include/simde/x86/../simde-common.h:68:45: note: in expansion of macro 'HEDLEY_STATIC_CAST'
   68 | #  define SIMDE_CAST_ALIGN(alignment, T, v) HEDLEY_STATIC_CAST(T, v)
      |                                             ^~~~~~~~~~~~~~~~~~
../debian/include/simde/x86/avx.h:4338:4: note: in expansion of macro 'SIMDE_CAST_ALIGN'
 4338 |   *SIMDE_CAST_ALIGN(32, simde__m256d*, mem_addr) =  a;
      |    ^~~~~~~~~~~~~~~~
```
Compile flags:
> g++ -DLAST_INT_TYPE=unsigned -DALPHABET_CAPACITY=64 -Wdate-time -D_FORTIFY_SOURCE=2 -DHAS_CXX_THREADS -DSIMDE_ENABLE_OPENMP -fopenmp-simd -O3 -g -O2 -fdebug-prefix-map=/build/last-align-1021=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wextra -Wcast-qual -Wswitch-enum -Wundef -Wcast-align -Wno-long-long -ansi -pedantic -std=c++11 -DSIMDE_ENABLE_OPENMP -fopenmp-simd -O3 -std=c++2a -I.

**Comment by mr-c** [comment]
The full patch: https://salsa.debian.org/med-team/last-align/blob/simde/debian/patches/simde

**Comment by nemequ** [comment]
Thanks for reporting it.  2e83ea8fb6852e0bb75bdcde0cd7c553263ec7c2 should fix it.

Once #56 is fixed I'll go through and convert all the C-style casts, but I don't want to get into that now :/

**Comment by mr-c** [comment]
Thank you @nemequ for https://github.com/nemequ/simde/commit/2e83ea8fb6852e0bb75bdcde0cd7c553263ec7c2!

Progress report: https://salsa.debian.org/med-team/last-align/tree/simde

Everything compiles, and I added the logic to cycle through the various `-m{avx2,avx,sse4.1,ssse3,sse3,sse2}` (amd64) or `{-m{sse3,sse2,sse,mmx},}` (i386 (really i686)) but **upon review the binaries produced are identical**!

Maybe `gcc--O3` found a better path than the SIMD intrinsics?

Sample compile command from the amd64 build:
`
g++ -Wdate-time -D_FORTIFY_SOURCE=2 -DHAS_CXX_THREADS -DSIMDE_ENABLE_OPENMP -g -O2 -fdebug-prefix-map=/build/last-align-1021=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wextra -Wcast-qual -Wswitch-enum -Wundef -Wcast-align -Wno-long-long -ansi -pedantic -std=c++11 -fopenmp-simd -O3 -mavx2 -Wl,-z,relro -Wl,-z,now -pthread -o lastdb-avx2 Alphabet.o CyclicSubsetSeed.o LambdaCalculator.o ScoreMatrix.o SubsetMinimizerFinder.o TantanMasker.o fileMap.o cbrc_linalg.o mcf_substitution_matrix_stats.o tantan.o LastdbArguments.o MultiSequence.o MultiSequenceQual.o SubsetSuffixArray.o SubsetSuffixArraySort.o lastdb.o -lz
`

**Comment by nemequ** [comment]
Is that the command you're cycling through?  All it is doing is linking the *.o files together, not really compiling anything.  If you want the binary to change you need to recompile the object files.

**Comment by mr-c** [comment]
@nemequ I'm cyling through all of `make all` and scrubbing the `*.o` in between. I'll dump a full build log into a gist later today. Thanks for checking!

**Comment by mr-c** [comment]
@mr-c here's the full log https://gist.github.com/mr-c/8924fb0bc0af88463744a66dad23558c

**Comment by mr-c** [comment]
Hmm. maybe I'm not cleaning up enough: `-mavx2` appears 91 times but `-msse4.1` appears only 54 times..

**Comment by mr-c** [comment]
okay, I pushed a change to clean up the `*.o{,8}` files better, but no change to the final output. Perhaps this project's SIMD usage is still in development..

**Comment by mr-c** [comment]
(for example, they never define the `WANT_AVX2` flag that their code looks for

**Comment by nemequ** [comment]
FWIW, I cleaned up a lot of those warnings last night… 37c74d3b1a3918c9128d197ca75b471a4485f1e2 should eliminate a lot of noise in the build log.

I'll play around with it today and see if I can figure out what's going on.

**Comment by mr-c** [comment]
@nemequ Thanks! I've rebuilt with the latest SIMDe and posted the new log at https://gist.github.com/mr-c/8924fb0bc0af88463744a66dad23558c#file-2019_12_20_last-align_1021-3_amd64-build (the binaries are still identical)

**Comment by nemequ** [comment]
I've tried with Fedora 31 and Debian Unstable.  With this (be careful, there is a `git clean -xdf` in there):

```bash
for SIMD in sse2 ssse3 avx avx2; do git clean -xdf; /usr/bin/make -j8 all SFX=-m${SIMD} CXXFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wextra -Wcast-qual -Wswitch-enum -Wundef -Wcast-align -Wno-long-long -ansi -pedantic -std=c++11 -Wno-misleading-indentation -fopenmp-simd -O3 -m$SIMD" CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wno-misleading-indentation -m$SIMD" CPPFLAGS="-Wdate-time -D_FORTIFY_SOURCE=2 -DHAS_CXX_THREADS -DSIMDE_ENABLE_OPENMP" LDFLAGS="-Wl,-z,relro -Wl,-z,now -pthread"; echo "$SIMD" >> ../simde.log; (cd src && sha1sum lastal lastal8 lastdb lastdb8 last-merge-batches last-pair-probs last-split last-split8 >> ../../simde.log); echo "" >> ../simde.log; done
```

I get

```
sse2
1ec023d3f2b68183ea2e6dc06d9855530af8dda8  lastal
410e45a0f90cb8e2a27b0b336397ce851ae050d0  lastal8
bddc6bc4850bb1e158d8b9a9400d595d3c257fdf  lastdb
47f44ec0a02f03e4add0ed88a5ab983395a52797  lastdb8
d518bed17b593dda13e95f259546e584cc1a179f  last-merge-batches
3c6859c3b5f17017ec097da815d8a503644f754f  last-pair-probs
ffce816213deeb10946d3179d358fd2267d8276a  last-split
54eaa101d6ebecb6c85dc827cb9f60cd334c3b85  last-split8

ssse3
4fcb90047200ca45deceb3c6cf1734c5bfe59cf1  lastal
071949312e494daf1e746298b8c3fb29b1c04bb1  lastal8
f675b135ef5cab49bf0d202c78d4ec3ca497995b  lastdb
cb3d9506acceac857e5bc6bed4aba063e80baa94  lastdb8
229f9658d55e6dd0bc321a6baa46848f394d9a51  last-merge-batches
717d1b3c854f17e43456a62865e74fbf5750381f  last-pair-probs
3c86e4e1ac81958dd71e1aab7bbde75976f114a5  last-split
7ec8485263db96ee98af13b5be8ddc0193434deb  last-split8

avx
b6f35565334d609274a7e68d92a3988708a674a5  lastal
e21e1a2bb33ad26529cc111c3f33fea87a0d1953  lastal8
c5e988e88d38c6d5e0ba691617143f47d3b8c414  lastdb
f5cc77a4d1b02c5d7d4a85793271f97eef996faf  lastdb8
22809ad2150c25ba8e39607bec29ebc4a6980046  last-merge-batches
b18fb3a3f8f97340f628ba92d868067bb7a328b9  last-pair-probs
833dd7a971aad21ed1148714a65ff36f4687ed14  last-split
e465265acc276d75063992582d6074aca7b59e8d  last-split8

avx2
00a9c657a88d9590b12b61a244a8195039f26a47  lastal
5b08af734740d69339a385283d2a30ed5f464b2a  lastal8
b71612afbfb3b26c19de8c30a7b7592c2f143022  lastdb
73da1c70d231a3a6503f457467deb74bf27fbf01  lastdb8
dc6cae8dbf5a766a1148723f3240950a52e92e90  last-merge-batches
b3bd259c00d5ba5ec1735523ed429b2a2a3ed68d  last-pair-probs
a89662d7e2d952e32ccceaa63c288daa4af7595c  last-split
db8968f42c214f802ec52ab8e0b5ee0d89661843  last-split8
```

I've run it multiple times and I get the same checksums, so the builds are reproducible.

`git clean -xdf` removes:

```
nemequ@peltast:~/local/src/last-align$ git:(master) 91A git clean -xdf
Removing src/Alignment.o
Removing src/Alignment.o8
Removing src/AlignmentPot.o
Removing src/AlignmentPot.o8
Removing src/AlignmentWrite.o
Removing src/AlignmentWrite.o8
Removing src/Alphabet.o
Removing src/Centroid.o
Removing src/Centroid.o8
Removing src/CyclicSubsetSeed.o
Removing src/DiagonalTable.o
Removing src/DiagonalTable.o8
Removing src/GappedXdropAligner.o
Removing src/GappedXdropAligner2qual.o
Removing src/GappedXdropAligner3frame.o
Removing src/GappedXdropAlignerPssm.o
Removing src/GeneticCode.o
Removing src/GreedyXdropAligner.o
Removing src/LambdaCalculator.o
Removing src/LastEvaluer.o
Removing src/LastalArguments.o
Removing src/LastdbArguments.o
Removing src/MultiSequence.o
Removing src/MultiSequence.o8
Removing src/MultiSequenceQual.o
Removing src/MultiSequenceQual.o8
Removing src/OneQualityScoreMatrix.o
Removing src/QualityPssmMaker.o
Removing src/ScoreMatrix.o
Removing src/SegmentPair.o
Removing src/SegmentPair.o8
Removing src/SegmentPairPot.o
Removing src/SegmentPairPot.o8
Removing src/SubsetMinimizerFinder.o
Removing src/SubsetSuffixArray.o
Removing src/SubsetSuffixArray.o8
Removing src/SubsetSuffixArraySearch.o
Removing src/SubsetSuffixArraySearch.o8
Removing src/SubsetSuffixArraySort.o
Removing src/SubsetSuffixArraySort.o8
Removing src/TantanMasker.o
Removing src/TwoQualityScoreMatrix.o
Removing src/alp/njn_dynprogprob.o
Removing src/alp/njn_dynprogproblim.o
Removing src/alp/njn_dynprogprobproto.o
Removing src/alp/njn_ioutil.o
Removing src/alp/njn_localmaxstat.o
Removing src/alp/njn_localmaxstatmatrix.o
Removing src/alp/njn_localmaxstatutil.o
Removing src/alp/njn_random.o
Removing src/alp/sls_alignment_evaluer.o
Removing src/alp/sls_alp.o
Removing src/alp/sls_alp_data.o
Removing src/alp/sls_alp_regression.o
Removing src/alp/sls_alp_sim.o
Removing src/alp/sls_basic.o
Removing src/alp/sls_falp_alignment_evaluer.o
Removing src/alp/sls_fsa1.o
Removing src/alp/sls_fsa1_parameters.o
Removing src/alp/sls_fsa1_pvalues.o
Removing src/alp/sls_fsa1_utils.o
Removing src/alp/sls_pvalues.o
Removing src/cbrc_linalg.o
Removing src/fileMap.o
Removing src/gaplessPssmXdrop.o
Removing src/gaplessTwoQualityXdrop.o
Removing src/gaplessXdrop.o
Removing src/last-merge-batches
Removing src/last-merge-batches.o
Removing src/last-pair-probs
Removing src/last-pair-probs-main.o
Removing src/last-pair-probs.o
Removing src/last-split
Removing src/last-split8
Removing src/lastal
Removing src/lastal.o
Removing src/lastal.o8
Removing src/lastal8
Removing src/lastdb
Removing src/lastdb.o
Removing src/lastdb.o8
Removing src/lastdb8
Removing src/mcf_gap_costs.o
Removing src/mcf_substitution_matrix_stats.o
Removing src/split/cbrc_split_aligner.o
Removing src/split/cbrc_split_aligner.o8
Removing src/split/cbrc_unsplit_alignment.o
Removing src/split/last-split-main.o
Removing src/split/last-split.o
Removing src/split/last-split.o8
Removing src/tantan.o
```

So *.o and *.o8, plus the executables.  Even if I change the `git clean -xdf` to `find src \( -name '*.o' -o -name '*.o' \) -exec rm -v {} \;` (just the *.o and *.o8 files, but I can still see what files are removed) I get different hashes.

Can you check the timestamps on the executables to make sure they are built at different times?  Also, maybe switch to the other version of the find command to see what files are actually being deleted and when?

Meanwhile, it looks like there are some extra warnings in that log that I'm not seeing on Fedora or Debian, I'll look into cleaning those up.

**Comment by mr-c** [comment]
@nemequ The error was on my side, thanks for checking!
