### ISSUE TITLE
Add more CPU architectures to CI

### ISSUE THREAD

**Issue by nemequ** [nemequ/simde#61]
I haven't used GitHub Actions for CI before, but it seems pretty interesting and would let us test on more platforms,  For example, [uraimo/run-on-arch-action](https://github.com/uraimo/run-on-arch-action) would let us build and test on armv6, armv7, aarch64, s390x, and ppc64le (and hopefully more in the future), which would be fantastic.

My current plan is to keep using Travis and AppVeyor for testing different versions of a few compilers, and use GitHub Actions for testing the latest GCC (and maybe clang) on other architectures.

I was playing around in a `wip/gh-ci` branch last night, but I think I'll play around in a different repo for a bit to get a feel for it instead of generating a lot of noise on SIMDe.  That said, if anyone is interested in helping out PRs are certainly welcome ;)

**Comment by junaruga** [comment]
> My current plan is to keep using Travis and AppVeyor for testing different versions of a few compilers, and use GitHub Actions for testing the latest GCC (and maybe clang) on other architectures.

Hello, Evan.

Just for your information. Travis started supporting x86_64, arm64, ppc64le and s390x.
https://docs.travis-ci.com/user/multi-cpu-architectures/

Here is the example of x86_64, i686, arm64, armv8 (=arm32) ppc64le and s390x.
https://github.com/junaruga/ci-multi-arch-native-test

If you have questions, here is the place to ask.
https://travis-ci.community/c/environments/multi-cpu-arch

**Comment by nemequ** [comment]
Wow, that's awesome!  I had no idea, thanks for letting me know.

It may still be a good idea to spread the load around a bit to avoid consuming too many resources on any one host, especially since they are providing these resources for free.  That said, right now I think we're a long way from abusing the service (and AFAIK nowhere near the limits), so that seems like a great way to get other architectures up and running.

It looks like multiple architectures may be easier on Travis than GitHub Actions, so maybe it would be better to reverse what I wrote above and use Travis to test multiple architectures and GitHub to test various compiler versions.  Unfortunately I already wrote scripts to help download and install [PGI](https://github.com/nemequ/pgi-travis) and [various TI compilers](https://github.com/nemequ/ti-compiler-install-travis)…

I'm going to change this issue to "Add more CPU architectures to CI", since that's what I really want.  Travis, GitHub Actions, etc. are just a means to that end :)

**Comment by junaruga** [comment]
You are welcome.
Yes, spreading the load might be a good idea. I see some projects using some CIs for that.

For example: Ruby project is using 3 CIs: 1. Travis for Linux CPU architectures compilers and flags cases, 2. Appveyor for Window case, and 3. GitHub Actions for other cases.
https://github.com/ruby/ruby

I think the scripts you wrote are still useful for some cases. Thanks for sharing it.

Here is my favorite example using various compilers in Travis.
https://github.com/microsoft/GSL

**Comment by nemequ** [comment]
Nice, thanks for the examples.

FWIW, [Hedley](https://github.com/nemequ/hedley/) is a good example, too.  It has GCC, clang, PGI, and several TI compilers on Travis CI, as well as Pelles and various versions of Visual Studio on AppVeyor.

**Comment by junaruga** [comment]
I see Hedley is really a good example. Thanks for sharing it.

Out of curiosity, why did you chose especially the PGI and TI compilers in the [list of compilers](https://en.wikipedia.org/wiki/List_of_compilers)?

**Comment by nemequ** [comment]
Mostly because they can be installed on Travis.  I'd love to add more.

I used to have [support for ICC](https://github.com/nemequ/icc-travis/), but some changes Intel made to their licensing software broke it.  There is actually some hope there with the new OneAPI stuff, but I haven't had time to look at it.

Hedley also theoretically supports a few compilers I can get manuals for but not the actual compilers, such as Cray.  Obviously those aren't an option.  Nor, of course, are the compilers I can't even get a manual for, much less the actual compiler (Green Hills and Wind River, for example).

Some (ARM and IAR) have evaluation versions we could use, but AFAICT there is no way to automatically install and run them.

CompCert doesn't have binaries available, and the license may be a problem (just because something is open source doesn't mean it's non-commercial).  I think this could actually be solved with a bit of effort (and maybe an e-mail or two to the maintainer about the license issue), but really it's probably not the best use of my time.  CompCert is a *really* cool project, but I feel like most of the people who need it aren't going to be pulling in much code from open-source projects, so CI support for it wouldn't really benefit the community much.

XL C/C++ is actually freely available **on ppc64le**.  Until recently there wasn't really a good way to test on POWER so I had to occasionally boot up a VM under emulation to test stuff manually, but now Travis and GitHub Actions can to PPC I'll probably be adding it at some point.

Hedley also gets tested on Pelles and MSVC (on AppVeyor).

AOCC is basically clang.  I've played with it a bit, and I honestly don't see what we would gain by testing on it in addition to clang.  Other compilers are clang-based, but AOCC seems to track clang *really* closely, to the extent that it just feels like AMD's development branch of clang.  It would just suck up a ton of resources to DL and install it, and that doesn't feel fair to the people generously donating their resources so OSS can have CI.

All the other compilers I can think of are no longer supported and I don't feel a strong desire to support compilers that their developers don't support.  TCC and DMC would probably be feasible (and are in fact supported by Hedley), and I'd probably accept patches to add them to CI, but I doubt I'll ever put in the time myself.

**Comment by junaruga** [comment]
Thanks for explaining the situation for the compilers. I am not familiar with that. But it is useful information for me.

By the way, I tried Travis on my forked repository adding following `arch:` syntax.

```
+    - arch: arm64
+      env: C_COMPILER=gcc CFLAGS=-march=native
+      addons:
+        apt:
+          packages:
+          - cmake
+          - cmake-data
+    - arch: ppc64le
+      env: C_COMPILER=gcc
+      addons:
+        apt:
+          packages:
+          - cmake
+          - cmake-data
+    - arch: s390x
+      env: C_COMPILER=gcc
+      addons:
+        apt:
+          packages:
+          - cmake
+          - cmake-data
```

Here is the [CI result](https://travis-ci.org/junaruga/simde/builds/635666008)

* `arch: arm64`: ok
* `arch: ppc64le`: ok
* `arch: s390x`: some test failures ("1705 of 1741 (98%) tests successful, 0 (0%) test skipped.")

I appreciate it if you take a look at the Travis log.

**Comment by junaruga** [comment]
Thank you for working!
Seeing the latest `wip/travis` branch's `.travis.yml`, 

Let me report the issues I found.

1. For ppc64le case, the last line: `arch: arm64` is unintentionally used.

```
  - name: "ppc64le"
    arch: ppc64le
    env:
    - ARCH_FLAGS="-mcpu=native"
    addons:
      apt:
        packages:
        - gcc
        - g++
    arch: arm64
```

2. Note about the behavior of the multiple commands in a single YAML block format.

I see 2 parts using multiple commands in a YAML block format.
In my understanding, only last command's exit status is checked by Travis.

```
  - name: "xlc"
    arch: ppc64le
    install:
    - |
      wget -q https://public.dhe.ibm.com/software/server/POWER/Linux/xl-compiler/eval/ppc64le/ubuntu/public.gpg -O- | sudo apt-key add -
      echo "deb https://public.dhe.ibm.com/software/server/POWER/Linux/xl-compiler/eval/ppc64le/ubuntu/ ${TRAVIS_DIST} main" >> /etc/apt/sources.list
      sudo apt-get update
      export XLC_VERSION="$(apt-cache search '^xlc\.[0-9]+\.[0-9]+\.[0-9]+$' | awk '{ print $1 }' | cut -b5-)"
      sudo apt-get install "xlc.${XLC_VERSION}" "xlc-license-community.${XLC_VERSION}"
      sudo /opt/ibm/xlC/${XLC_VERSION}/bin/xlc_configure <<< 1 >/dev/null
```

```
- |
  if [ -n "${C_COMPILER}" ]; then
    export CC="${C_COMPILER}"
  fi
  if [ -n "${CXX_COMPILER}" ]; then
    export CXX="${CXX_COMPILER}"
  fi
```

That means when you put `ls foobar` returning the error exist status every time except last line, it passes unintentionally possibly.
The solution is using `&&` or using multiple block formats `- |`.

```
$ git diff
diff --git a/.travis.yml b/.travis.yml
index f22201a..e48f9cb 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -74,6 +74,7 @@ jobs:
     install:
     - |
       wget -q https://public.dhe.ibm.com/software/server/POWER/Linux/xl-compiler/eval/ppc64le/ubuntu/public.gpg -O- | sudo apt-key add -
+      ls foobar
       echo "deb https://public.dhe.ibm.com/software/server/POWER/Linux/xl-compiler/eval/ppc64le/ubuntu/ ${TRAVIS_DIST} main" >> /etc/apt/sources.list
       sudo apt-get update
       export XLC_VERSION="$(apt-cache search '^xlc\.[0-9]+\.[0-9]+\.[0-9]+$' | awk '{ print $1 }' | cut -b5-)"
```

**Comment by nemequ** [comment]
Thanks for the review!  I guess it's hard to miss like 50 commits to a branch when you're watching the repo (sorry everyone!).

That first item is definitely a bug.  Good catch.

As for the second item, that's a good point.  It doesn't really matter here since that `/opt/ibm/xlC/*/bin/xlc_configure` is going to fail if any of the preceding items didn't work, but it's probably a good idea not to get in the habit of relying on that.

My thinking was that it would be nice to have a single YAML value to group together what I consider to be one step (in this case, "install XL C/C++").  Looking at it again, though, I think it's already pretty clear by just having the install step being fully dedicated to the task.  I'll go ahead and change it.

For now I think the only thing blocking this is the clang error.  I'm going to spin up a bionic VM to try to figure that out since I'm not able to reproduce it on Fedora 31 (clang 9, bionic is clang 7).

**Comment by junaruga** [comment]
> For now I think the only thing blocking this is the clang error. I'm going to spin up a bionic VM to try to figure that out since I'm not able to reproduce it on Fedora 31 (clang 9, bionic is clang 7).

If you are using Feodra 31,  using `ubuntu:bionic` container with `podman` might help you to reproduce it on your Fedora 31.

On the project directory.

```
$ pwd
/home/jaruga/git/simde
```

Prepare following `Dockerfile`.

```
$ cat Dockerfile 
FROM ubuntu:bionic

RUN apt-get update
# https://packages.ubuntu.com/bionic-updates/clang-7
RUN apt-get -y install clang-7
RUN clang-7 --version

WORKDIR /work
COPY . .
```

Install podman if you have not installed it yet.

```
$ sudo dnf install podman
```

Then build the container base on the `Dockerfile`.

```
$ podman build --rm -t test/bionic .
```

Run the built container interactively.

```
$ podman run --rm -it test/bionic bash
root@06d3b1abc967:/work# clang-7 --version
clang version 7.0.0-3~ubuntu0.18.04.1 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

root@06d3b1abc967:/work# ls
COPYING  Dockerfile  README.md  simde  test
```

**Comment by junaruga** [comment]
> Thanks for the review! I guess it's hard to miss like 50 commits to a branch when you're watching the repo (sorry everyone!).

@nemequ I see you are now using `nemequ/ci-noise` repository.
Personally I am happy to watch your many commits in this repository too.
I think other people do.
They can unsubscribe the "watch" if they are not comfortable.
I think you can just do your comfortable way to work.

**Comment by nemequ** [comment]
Okay, I finally managed to get this merged.  Thanks @junaruga for all the help!  I'm actually quite happy with the new Travis integration, I'm going to try to port some of my other projects to a similar structure.

It includes ppc64le, aarch64, and s390x builds, and I did manage to get XL C/C++ running (it doesn't quite work with SIMDe yet, I'll try to get to that soon). There are also some surprising s390x errors that I'm not yet sure how to resolve, but I'll try to get to them soon.

> If you are using Feodra 31, using ubuntu:bionic container with podman might help you to reproduce it on your Fedora 31.

I wasn't able to reproduce the issue with this (or with a VM), but it worked quite well.  I've never really been very happy with Docker for stuff like this, but this goes a long way toward changing my mind.  I'm sure I'll be using that in the future, thanks!

The issue seems to only occur when AVX512 is supported, which sadly rules out all of my hardware :(.  I tried building everything in Intel's [Software Development Emulator](https://software.intel.com/en-us/articles/intel-software-development-emulator/), but it didn't work at all in Docker and it made clang crash in the VM.  I ended up just creating special cases to force the compiler to use a portable implementation if `__clang__` and `__AVX512F__` are both defined, hopefully that's sufficient.

> @nemequ I see you are now using nemequ/ci-noise repository.
> Personally I am happy to watch your many commits in this repository too.
> I think other people can unsubscribe the "watch" if they are not comfortable.
> I think you can just do your comfortable way to work. And it's up to you.

Thanks.  I'm only planning on using the ci-noise repo when I know there are going to be a ton of commits just to try different things on CI that I can't really do on hardware I own.  For example, working on .travis.yml or guessing at how to fix issues on a platform I don't have interactive access to.  I've always felt a bit weird about pushing all that stuff out to the main repo, so maybe this is more about me than people watching the repo, but honestly I feel a lot more comfortable with a separate repo.

Either way, I definitely prefer for commits that reach master to have most of the mistakes filtered out.  I love how RCS can help show how the code evolved and why things are the way they are, but at the same time I don't like a lot of noise in that story.  A separate repo just helps limit that noise for people who are watching the main repository, and it's really no more effort for me (I'm just doing `git push ci branch` instead of `git push origin branch`).

**Comment by nemequ** [comment]
@junaruga since you were asking about compilers: I just got an Intel C/C++ Compiler build working, too. Apparently Intel changed how they do the licensing for ICC when they put together the onAPI stuff, and now it just works.

ICC is a really good compiler, but for me the killer feature is the optimization reports, which are way better than anything you can get from GCC or clang.  If you have performance-sensitive code they're definitely worth a look.
