### ISSUE TITLE
Participate in Google Summer of Code?

### ISSUE THREAD

**Issue by mr-c** [nemequ/simde#66]
Possibly as part of the Open Bioinformatics Foundation.

**Comment by nemequ** [comment]
I hadn't considered it, but I'm certainly open to the idea.  There is certainly more than enough to do in numerous areas…

**Comment by nemequ** [comment]
Any idea who I should talk to about this?  I'd be happy to be a mentor, but I'd definitely want to do it under some other organization's umbrella.

The obvious ideas would be complete implementations of one ISA extension using another (only MMX with NEON is 100% complete so far, so lots of options), or a complete portable implementation of a new ISA extension.

**Comment by mr-c** [comment]
Yes, I recommend using some other organization that has already participated. There are over 200 to choose from :-) 

https://summerofcode.withgoogle.com/archive/2019/organizations/

I'm sure the Open Bioinformatics Foundation would be happy to have simde participate, but feel free to choose another organization if you find a better match. 

Other possible hosting organizations from skimming the list: Debian, LLVM, Mozilla

For OBF, we will be gathering proposals starting on January 14th at https://github.com/OBF/GSoC/tree/gh-pages

> The obvious ideas would be complete implementations of one ISA extension using another (only MMX with NEON is 100% complete so far, so lots of options), or a complete portable implementation of a new ISA extension.

:+1: 

Another idea would be to pick a SIMD-based application with real world test data as an optimization exercise: are we providing the best fallbacks for a given piece of hardware & compiler? More micro- and macro-benchmarking and performance regression CI would be welcome.

**Comment by mr-c** [comment]
I can also provide a list of Debian packages (scientific and otherwise) that only build on a subset of Debian's primary architectures due to the use of SIMD intrinsics. Prospective mentees could contact the authors/maintainers to see if there is interest in accepting a SIMDE enhancement.

This is a bit more advanced as it is likely to dig up many [x86-64-isms](https://wiki.debian.org/ArchitectureSpecificsMemo) in those codebases: endian assumptions, size of (void), size of (long double), char signedness and so forth.

**Comment by nemequ** [comment]
OBF sounds good to me, though I'm not really involved in that community.  I'm not sure they would appreciate some rando dropping by to suggest this.  I'd me happy to be the mentor, but would you mind if I dropped your name (I see you're listed as a potential mentor on some other projects)?

Maybe I could create a "GSoC" tag or something for the SIMDe issue tracker and we can just start opening up issues for ideas?

**Comment by mr-c** [comment]
Yes, please name drop me. You can also link to this issue.

The issue label is also a good idea!

>

**Comment by mr-c** [comment]
https://mailman.open-bio.org/pipermail/gsoc/2020/000980.html

**Comment by nemequ** [comment]
Thanks @mr-c, I'll try to put something together soon.

**Comment by nemequ** [comment]
I just submitted a couple proposals, just in the nick of time (for some reason I thought it was open until the 4th not the 2nd).  I didn't want to add you as a potential mentor without asking, but would you be interested?

Hopefully it gets picked up; I really think it would be a great learning experience (I know developing SIMDe has been for me), and would have widespread benefits.

**Comment by junaruga** [comment]
Evan, do you like giving a talk about simde in the Google Summer of Code?
If it will happen and it will be recorded, I like learning simde and instruction set watching the video. :)

**Comment by nemequ** [comment]
I wouldn't mind giving a talk about SIMDe, for GSoC or something else.  But I don't have any plans to do so right now, largely because I have no idea where to find a room full of people who would care to attend.  But suggestions are welcome :)

**Comment by nemequ** [comment]
I think we can close this given that GSoC is underway and we have two students participating.  Thanks @mr-c for making this happen!
