### ISSUE TITLE
Add clang on arm32 to CI

### ISSUE THREAD

**Issue by nemequ** [nemequ/simde#75]
Clang tends to do a much better job of warning (well, erroring) about out-of-range values being passed.  This can be a bit annoying because the checks are done before dead code elimination (so you can't do something like `(imm8 & ~15) ? vdup_n_s16(0) : vshl_s16(imm8)`), but it also catches a *lot* of bugs.

For now clang-9 is working on arm32, but I'd definitely like to get a CI build going before I start working on more ARM implementations.

@junaruga, maybe you happen to know of an example we could use?

**Comment by junaruga** [comment]
> @junaruga, maybe you happen to know of an example we could use?

Hi, I am happy to assist this.
Thank you for explaining the context to use clang.

I do not know the exact example for "clang-9 on arm32".
But I know some clues.

## clang-9 and clang-8

clang-8 on amd64 (x86_64) is example with "llvm-toolchain-xenial-8" repository.
https://github.com/ruby/ruby/blob/master/.travis.yml#L99

And it seems that `llvm-toolchain-bionic-9` repository is available on [llvm web site](https://apt.llvm.org/). Maybe we can use the repository.

> deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main
> deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main

## arm32

And for arm32 case, I introduced you the example for "gcc on arm32" you.

I will try to run "clang-9 on arm32 to CI" on my forked repository.

**Comment by nemequ** [comment]
Thanks.

I used that repo for a clang-9 for amd64 build, it works great.

I'm just not sure how to get it to cross-compile to arm32 in a way that will be usable to run tests; it's not like GCC where you install an `arm-linux-gnueabihf-gcc` and just use that.  Clang is [natively a cross-compiler](https://clang.llvm.org/docs/CrossCompilation.html), I just have no idea what values to pass.

All the examples I can find want me to DL a sysroot for a board (usually a RPi) to target, but this needs to target Ubuntu 18.04 arm32.  Seems like it should be easier, but I guess nobody is bothering.

**Comment by junaruga** [comment]
Perhaps `- CFLAGS="-target armv8l-unknown-linux-eabihf"` might be used for the `clang-9 on arm32`.

I am still working in progress [here](https://github.com/junaruga/ci-multi-arch-native-test/blob/wip/travis-arm32-clang/.travis.yml).

I also found the [reference doc](https://releases.llvm.org/9.0.0/tools/clang/docs/ClangCommandLineReference.html) and [target doc](https://collaborate.linaro.org/display/TCWGPUB/ARM+and+AArch64+Target+Triples).

If we can not run it on Travis CI, possibly the easy way is to use [Drone CI's arm32 mode](https://github.com/junaruga/ci-multi-arch-test/blob/master/.drone.yml#L27).

**Comment by nemequ** [comment]
Awesome, thanks for looking into this!

I had no idea Drone had arm32 available, that sounds like an excellent way to go.  Besides, it wouldn't be a bad idea to spread the load around a bit to avoid gobbling up too many of Travis' resources.  I'll try to get that up and running this week.

**Comment by nemequ** [comment]
Fixed with #128.  Thanks for supplying the patch :)
