### ISSUE TITLE
Improve compile-time checks for shifting by scalar

### ISSUE THREAD

**Issue by nemequ** [nemequ/simde#77]
There are a ton of functions that shift a vector by a scalar.  We should do what we can to validate the range at compile-time.  For most of there functions the scalar is an immediate mode (a compile-time constant is required).

For functions (*i.e.*, the portable fallbacks), we should use the [`HEDLEY_REQUIRE_MSG`](https://nemequ.github.io/hedley/api-reference.html#HEDLEY_REQUIRE_MSG) macro, which compiles to a `diagnose_if` attribute in clang.  There are a bunch of examples in avx.h, we should just be doing something similar in sse, sse2, *etc.*.  Here is an example patch:

```c
diff --git a/simde/x86/sse2.h b/simde/x86/sse2.h
index b2a7174..925b109 100644
--- a/simde/x86/sse2.h
+++ b/simde/x86/sse2.h
@@ -3925,7 +3925,8 @@ simde_mm_sra_epi32 (simde__m128i a, simde__m128i count) {
 
 SIMDE__FUNCTION_ATTRIBUTES
 simde__m128i
-simde_mm_slli_epi16 (simde__m128i a, const int imm8) {
+simde_mm_slli_epi16 (simde__m128i a, const int imm8)
+    HEDLEY_REQUIRE_MSG((imm8 & 15) == imm8, "imm8 must be in range [0, 15]") {
   simde__m128i r;
 
   const int s = (imm8 > HEDLEY_STATIC_CAST(int, sizeof(r.i16[0]) * CHAR_BIT) - 1) ? 0 : imm8;
```

The [Intel documentation](https://software.intel.com/sites/landingpage/IntrinsicsGuide/)  makes it clear for a lot of these functions that values outside of the expected range are acceptable (i.e., you can shift an `int16_t` by 100 bits) as they just use `imm8 & 0xff`, but clang (and sometimes gcc) will often emit an error, which I think is the right choice; clearing should be done with one of the setzero functions.

This would be an excellent first issue for someone to help introduce you to the codebase by doing something useful for a lot of people.

**Comment by masterchef2209** [comment]
Hi, i am a 3rd year computer science undergraduate , i am interested in working on this project as a GSoC student. I am comfortable in writing C/C++ code. I don't have any previous experience with SIMD, but i have read about it and i understand what it is about.

**Comment by masterchef2209** [comment]
I understand what needs to be done in this issue, but i am not sure how to know the range of imm8 for different functions. I can get an idea from the docs but how to know if it is correct.

**Comment by nemequ** [comment]
Hi, that would be great!  Please feel free to ask about anything you don't understand.

Good question.  Unfortunately the documentation doesn't really specify this explicitly; often you'll have to understand the basics of how the function works to know what the right range should be.

In the case of `_mm256_extractf128_pd`, take a look at the pseudo-code for [`_mm256_extractf128_pd`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm256_extractf128_pd&expand=2436,2436) on Intel's Intrinsics Guide:

```
CASE imm8[7:0] OF
0: dst[127:0] := a[127:0]
1: dst[127:0] := a[255:128]
ESAC
dst[MAX:128] := 0
```

Notice that the only two possible values are 0 and 1.

For other functions it may be a bit more subtle.  For example, think about what would happen if the pseudo-code were:

```
dst[127:0] := a[((imm8[7:0] * 128) + 127) : (imm8[7:0] * 128)]
```

In this case you would have to know that values outside of [0, 1] would result in attempting to access data outside of the 256-bit `a` vector, which is illegal.  The pseudo-code doesn't usually do stuff like this since it's meant to be readable, but it can definitely be a bit difficult to decipher sometimes; if you have trouble please feel free to ask in this issue and I'll try to help.

Also, sometimes reading the documentation for the instruction (instead of the intrinsic) can be helpful.  For example, the intrisics guide specifies that `_mm256_extractf128_pd` is implemented using [vextractf128](https://www.felixcloutier.com/x86/vextractf128:vextractf32x4:vextractf64x2:vextractf32x8:vextractf64x4).  The documentation for `vextractf128` has a description which may be helpful.  I usually find the pseudo-code much easier to read, but sometimes seeing in phrased a bit differently can help things click into place.

**Comment by masterchef2209** [comment]
I have created a PR, can you please tell me if it is fine so that i can start working on other files.
Thank You

**Comment by masterchef2209** [comment]
can you please see why are the checks failing in my PR? I am unable to figure out the what i am doing wrong.
Thank You

**Comment by nemequ** [comment]
You're not doing anything wrong, CodeCov failing was the problem, sorry.  The patch looks good, thanks!

**Comment by masterchef2209** [comment]
I have added patches for more files and created a PR , if i have missed any files for this issue please inform me.
Thank You

**Comment by nemequ** [comment]
Merged, thanks @masterchef2209!
