### ISSUE TITLE
Missing alias for _mm_load1_ps

### ISSUE THREAD

**Issue by abrown** [nemequ/simde#82]
I noticed that the alias for `simde_mm_load1_ps` seems to be missing. The equivalent intrinsic, `simde_mm_load_ps1`, does seem to have an alias but the code I am attempting to compile expects `_mm_load1_ps` to be available:

https://github.com/nemequ/simde/blob/master/simde/x86/sse.h#L1562-L1564

**Comment by nemequ** [comment]
Should be fixed by 45a2edd1408a26534ea1b3a65676022eb4d6632c, thanks for reporting!
