### ISSUE TITLE
Possible problem with uppercase Windows.h header on Linux/Mingw/Wine

### ISSUE THREAD

**Issue by Flix01** [nemequ/simde#83]
I've seen that *simde/x86/sse.h* includes `<Windows.h>` uppercase.

Although it should be correct, that might cause problems in some versions of Mingw (well, mine...) on case-sensitive filesystems, where `<windows.h>` is present.

I'm not sure what's the best practice in these cases... just wanted to report a possible issue.

**Comment by nemequ** [comment]
Sounds good to me.  Fixed, thanks.
