### ISSUE TITLE
big endian issues

### ISSUE THREAD

**Issue by mr-c** [nemequ/simde#85]
With s390x
~~`1622 of 1654 (98%) tests successful, 0 (0%) test skipped.`~~
`1636 of 1654 (99%) tests successful, 0 (0%) test skipped.`

https://travis-ci.org/nemequ/simde/jobs/648919336

**Comment by nemequ** [comment]
Wow, excruciatingly close!  I think the problems are actually in the tests not SIMDe, which explains why so many have been resolved since I disabled the s390x build.

Thanks for pointing this out.  I'll try to look at this soon (likely tomorrow)… I finally figured out some problems with MSVC on x86 which have been driving me crazy, I want to finish fixing that first.

**Comment by nemequ** [comment]
I took care of a bunch of these (1636 are working now), but for the rest I'm going to need access to a big endian machine.  I just requested access to the [GCC Compile Farm](https://gcc.gnu.org/wiki/CompileFarm), which has a ppc64 machine.  They also have ppc64le, mips, mips64, sparc64… lots of testing potential :)

Most of the remaining items are shifts.  I think most of them I should be able to either do some byte swapping or ifdef for endianness.  Other than than it's just `_mm_maskstore_ps`, which has me a little confused TBH… hopefully looking at it with fresh eyes once (and having access to a BE machine will help).

I added the s390x build back in to Travis.  It's allowed to fail for now, of course, but it'll be there nagging me until I fix it.

**Comment by junaruga** [comment]
> I just requested access to the GCC Compile Farm, which has a ppc64 machine. They also have ppc64le, mips, mips64, sparc64… lots of testing potential :)

The "GCC Compile Farm" looks great and very useful. Thank you for sharing it. :)

**Comment by mr-c** [comment]
For a real world example, see https://buildd.debian.org/status/fetch.php?pkg=libssw&arch=s390x&ver=1.1-7&stamp=1581764340&raw=0

**Comment by nemequ** [comment]
Done!  All test cases are passing on s390x.  And big endian MIPS, FWIW.

I haven't heard anything back about the GCC Compile Farm, but between abusing Travis CI and an absurdly slow MIPS emulator (hence the bit above about working on MIPS) I managed to figure everything out.

**Comment by mr-c** [comment]
Woo-hoo!
