### ISSUE TITLE
study OpenCV's "Wide Universal Intrinsics"

### ISSUE THREAD

**Issue by mr-c** [nemequ/simde#87]
https://docs.opencv.org/master/df/d91/group__core__hal__intrin.html

https://github.com/opencv/opencv/tree/master/modules/core/include/opencv2/core/hal

(discovered at https://github.com/opencv/opencv/wiki/GSoC_2020#idea-optimize-opencv-for-risc-v )

**Comment by nemequ** [comment]
Thanks, I don't remember seeing that one before.

I just added an [Alternatives](https://github.com/nemequ/simde/wiki/Alternatives) page on the wiki to collect all of these, **please** let me know if you find more.  It would be great for me to have a list of projects like this to consult from time to time to help with SIMDe development, and I'm guessing other people would find it useful to find an alternative to SIMDe (hence the title).

I think they did a pretty good job with the API.  It's obviously targeted at CV applications so there are some gaps in the API, but overall it seems solid… much more consistent (and sane) than Intel's, and more readable than NEON, but I can see a lot of influence from both.

I'll definitely refer to it in the future for ideas on how to implement specific functions; they've already ported it to a lot more architectures than SIMDe has optimized implementations for, so it will probably be extremely valuable when adding POWER, MIPS, etc.

A GSoC project is probably premature; AFAIK they're still working on the SIMD RISC-V specification, and haven't even started looking at defining a C-level API.
