### ISSUE TITLE
Help with GSOC problem statement

### ISSUE THREAD

**Issue by VedantParanjape** [nemequ/simde#90]
**Problem Statement => SIMDe: Add new implementations of ISA extensions**

Could you provide me with some documentation of what are ISA extension. Given content is scant.

Thanks

**Comment by nemequ** [comment]
Sure.

ISA is "Instruction Set Architecture".  Examples include x86, ARM, POWER, RISC-V, MIPS, SPARC, etc.

The SIMD instructions for a given ISA are typically not considered to be part of the core ISA, but are instead implemented as extensions.  Examples include SSE/AVX (for x86/x86_64), NEON and MVE (for ARM/AArch64), AltiVec/VMX (for POWER), MSA (for MIPS), and VIS (for SPARC).

Basically, in the context of SIMDe, ISA extension refers to the architecture-specific SIMD instructions.

SIMDe uses one ISA extension to implement the API of another ISA extension.  For example, using NEON to implement SSE.  That's what this is referring to.

The other GSoC proposal is to create a portable implementation of a currently unimplemented ISA extension.  For example, implementing NEON using code that will work on virtually any C99 compiler, much like what we already have in place for SSE/SSE2/SSE3/SSSE3/SSE4.1/AVX.

**Comment by VedantParanjape** [comment]
Thanks for the help !
